### ISSUE TITLE
AppImage Request

### ISSUE THREAD

**Issue by ElectricPrism** [notepadqq/notepadqq#308]
Some users report that they would like to try Notepadqq but it's not currently available on their system.

How hard would it be to have a build bot create a Notepadqq AppImage to increase the user base? (Other apps like Krita are already doing this with great success)

http://appimage.org

**Comment by probonopd** [comment]
Shouldn't be hard at all, especially given that this project is already building on Travis CI. See [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) and especially the [Travis CI examples](https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt) linked there. Basically `linuxdeployqt -appimage` can do it automatically for you.

**Comment by danieleds** [comment]
If someone wants to try working on this, I'm fully supporting the idea of having official Notepadqq AppImages.

**Comment by probonopd** [comment]
@danieleds I tried to convert the deb from the trusty ppa to an AppImage but I get

> Install a newer Qt version (≥ 5.3) from the official repositories of your distribution.

It would be nice if the deb in the trusty ppa would be packaged in a way that uses https://launchpad.net/~beineri/+archive/ubuntu/opt-qt57-trusty, then it would also be easier to convert the deb from the trusty ppa to an AppImage using this simple `.yml` file and the meta [Recipe](https://raw.githubusercontent.com/probonopd/AppImages/master/recipes/meta/Recipe):

```
app: Notepadqq

ingredients:
  dist: trusty
  sources: 
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe
  ppas:
    - notepadqq-team/notepadqq
    - beineri/opt-qt57-trusty
```
